name: Fishtank Dry Run

on:
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: pr-dry-run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dry-run-build:
    name: Dry run build of Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      NW_CONFIG: ${{ github.workspace }}/config.json

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v6
        with:
            repository: vigneshsubbaram/fishtank
            ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push ssh
        uses: docker/build-push-action@v6
        with:
          context: "https://github.com/vigneshsubbaram/raikou-net.git#main:components/ssh"
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/ssh:v1.2.0
            ghcr.io/${{ github.repository_owner }}/ssh:latest
          cache-from: type=gha,scope=ssh
          cache-to: type=gha,mode=max,scope=ssh

      - name: Pull ssh into local daemon for downstream builds
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/ssh:v1.2.0
          docker tag ghcr.io/${{ github.repository_owner }}/ssh:v1.2.0 ssh:v1.2.0

      - name: Build ota-base (dry run)
        env:
              DOCKER_BUILDKIT: 0
              COMPOSE_DOCKER_CLI_BUILD: 0
        run: |
          docker compose build ota-base
          docker tag ota-base ghcr.io/${{ github.repository_owner }}/ota-base:container_utils_1.1.1

      - name: Build ota-server (dry run)
        env:
              DOCKER_BUILDKIT: 0
              COMPOSE_DOCKER_CLI_BUILD: 0
        run: |
          docker compose build ota-server

      - name: Build mtt (dry run)
        env:
              DOCKER_BUILDKIT: 0
              COMPOSE_DOCKER_CLI_BUILD: 0
        run: |
          docker compose build mtt

      - name: Build orchestrator (dry run)
        env:
              DOCKER_BUILDKIT: 0
              COMPOSE_DOCKER_CLI_BUILD: 0
        run: |
          docker compose build orchestrator
